### ISSUE TITLE
ls & lsdir always returns base path instead of full

### ISSUE THREAD

**Issue by glerchundi** [kelseyhightower/confd#181]
I dont know if this is an expected behaviour but when I do this (following the example of [templates document](https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#create-the-template-1)):

```go
{{range $dir := lsdir "/services/web"}}
$dir: {{$dir}}
base $dir: {{base $dir}}
{{end}}
```

This is what it renders:
```
$dir: cust1
base $dir: cust1
$dir: cust2
base $dir: cust2
```

But I would expect this instead:
```
$dir: /services/web/cust1
base $dir: cust1
$dir: /services/web/cust2
base $dir: cust2
```

Obviously, if a prefix was used, this shouldn't be part of the full path.

If it was made in this way intentionally maybe removing ```upstream {{base $dir}}``` from templating doc. would be a good idea?

thanks!

**Comment by bacongobbler** [comment]
To confirm, this seems to be the case when `lsdir` is being described in the unit tests: https://github.com/kelseyhightower/confd/blob/b05600f639d7542500e6aefe53a18faf23cd855f/resource/template/template_test.go#L289-L291

**Comment by glerchundi** [comment]
yes, i would expect: 
```

value: /test/data/def

value: /test/data/jkl

```

thanks

**Comment by bacongobbler** [comment]
@kelseyhightower is this the intended behaviour that we want? i.e. `lsdir`/`ls` returning the full path instead of the base path

**Comment by bacongobbler** [comment]
Looks like this is (partially) out of our hands unless we update memkv: 

https://github.com/kelseyhightower/memkv/blob/7f9c7f36f45ba80c62fe22779ee78d9b4ca36580/store.go#L127

https://github.com/kelseyhightower/memkv/blob/7f9c7f36f45ba80c62fe22779ee78d9b4ca36580/store.go#L144

**Comment by kelseyhightower** [comment]
This is by design. For some users returning the base dir is desirable because they don't have to use base function to get the base path. For other users returning the full path is nice because they don't have to join the base dir with root key.

The decision was made in confd to follow the output from the ls unix command and only return the base path by default and force users to join the root path inside the template. This was done to offer the most flexibility at the cost of requiring the join command to produce the full key.
