### ISSUE TITLE
support export values from other backends as env variables?

### ISSUE THREAD

**Issue by clescot** [kelseyhightower/confd#356]
Hi,
it would be useful to export by configuration some values grabbed from a not env backend, as env variables.
my use case : 
i grab my unknown host IP from rancher backend via confd, which will be used in a startup script.
actually, i need to put another template to export this value in a bash script.
It would be nice if confd export by configuration these grabbed values out of the box.

best regards,

Charles.

**Comment by kelseyhightower** [comment]
This issue makes me believe we need a general discussion around multiple sources for configuration values. The goal with confd is to have users pull all configuration, from multiple sources, and push them to a single configuration data store. This data store would become the source of truth for all configuration and would be the only source confd would pull from.

IMO this is the only way to keep things simple and make it much easier to troubleshoot what confd is doing. I also think it would give you the flexibility down the road where additional sources of configuration are needed.

I'm closing this issue not because this is a bad idea, but I feel it's out of scope for confd and I believe you will get better results pulling all the data you need into a single data store and pointing confd at that.
