### ISSUE TITLE
Logging to stderr instead of stdout

### ISSUE THREAD

**Issue by xynova** [kelseyhightower/confd#413]
Just noticed the logrus pgk is is directing to stderr by default

https://github.com/kelseyhightower/confd/blob/a7c2622e7071b9d6e36eeda73625e166af42fa61/vendor/github.com/Sirupsen/logrus/logger.go

I am guessing adding "log.SetOutput(os.Stdout)" to the init function would suffice?
https://github.com/kelseyhightower/confd/blob/master/log/log.go

**Comment by bacongobbler** [comment]
This is intentional. confd doesn't output any information to stdout because there isn't anything useful for the program to send other than command help usage. Is there a specific use case you're trying to resolve?

**Comment by xynova** [comment]
Nothing major. I was just running it with ansible which was marking the task as failed. I guess then the docs probably need a tiny update from all logs go to stdout to all logs go to stderr.

**Comment by dverbeek84** [comment]
I am displaying the log to the console with my own init system.
I make all the stdout write to info, so it is blue in my log. And when is read the stderr everything is red.
This way i can focus on the errors. So it make no sense zo log info to stderr.

**Comment by bacongobbler** [comment]
@dverbeek84 you can redirect stderr to stdout via `confd ... 2>&1`.

Following best conventions, a program should only output useful information that can be piped to another program to stdout. I thought that the logs confd spits out isn't useful to pipe to another program, so it's all sent to stderr. However, it can be argued that the logs `confd` produces at the INFO level is considered useful information to other programs, and anything diagnostic (DEBUG level) or critical errors (ERROR, WARNING levels) should be written to stderr.

@dverbeek84 does that seem to be the issue here?

**Comment by dverbeek84** [comment]
@bacongobbler Yes, this is indeed the issue.

**Comment by caio1982** [comment]
How about confd (with log level set to debug) taking over stdout and swallowing up my application logging to stdout that was spawned by confd in daemon mode? Is this something covered by the intentional behavior described? That's a Gunicorn app by the way, which logs to both stderr and stdout and you lose its logging if confd is spawning it.

**Comment by okushchenko** [comment]
The standard behavior of a program running on Linux is to write logs to stderr. If you want to parse the logs you can capture the stderr.

Closing this issue for now.

**Comment by hubo1016** [comment]
You may use redirect: `confd... 2>&1` to redirect stderr.
