### ISSUE TITLE
service + confd sidekick + kill -s HUP

### ISSUE THREAD

**Issue by mishak87** [kelseyhightower/confd#415]
*While using confd I frequently get to a point where having confd do just few more things would simplify the service.*

My regular use-case is packing old/non-docker service and confd as a sidekick generating config just once from ENV or metadata service. This is useful if the data is not the main config of a service since I can't send HUP to service container (pid is in different namespace). For example updating `.htaccess` file of web server.

#### I considered several ways how to solve it
* Extend [dumb-init](https://github.com/Yelp/dumb-init) to wait for files, watch for their changes using inotify and send HUP to child
  * :-1: needs to be baked inside main image
  * :+1: dumb-init system is usually already baked in the image

* Add inotify script or cron to send HUP to image
  * :-1:  another process unrelated to service in the image

* Using confd as an dumb-init system for the image that would send `kill -s HUP` on change
`confd -c 'command arg1 arg2'`

* Discover service from metadata (confd being privileged sidekick with docker client baked in) and run `docker kill -s HUP $(cat container name/id on host)`
*prototyping this at the moment*
  * :+1: Fast PoC
  * :-1: Everything from privilege to obscurity of that solution

* Force service to share a unix socket over which reload command could be sent

* Extend sharing process namespaces in docker from none and host to `pid: <container id/name>`

Am I the only one that encountered this? I would love to hear your opinion :-)

**Comment by bacongobbler** [comment]
I think what you're looking for is [`reload_cmd`](https://github.com/kelseyhightower/confd/blob/master/docs/quick-start-guide.md#create-template-resources). Would that solve your use case?

**Comment by mishak87** [comment]
@bacongobbler No. reload_cmd implies you have process manager inside the container and it is a blackbox essentially - can't use stdin, stdout; process management is all hidden from container scheduler. By decomposing it to watch files and HUP and putting confd to sidekick you have nearly all benefits as you would have by running single process in the container with the bonus of updating the service without restart.

**Comment by bacongobbler** [comment]
Can you please try to decompose your problem down to a feature request or a solid use case example? From grokking the issue I cannot see what the issue is here and how we'd resolve it in confd. From your third point,

> Discover service from metadata (confd being privileged sidekick with docker client baked in) and run `docker kill -s HUP $(cat container name/id on host)`
> prototyping this at the moment

That seems to be the way you'd use `reload_cmd` on any changes from your backend, whether that's the environment, etcd, consul or any other supported backend:

```
reload_cmd = docker kill -s HUP service-container
```

Most people are quite happy with that solution. Containers should be treated like black boxes, and sending SIGHUP to a container should reload the main process running inside it. Either that or

```
reload_cmd = docker exec service-container /bin/reload
```

Could be another solution.

I'm not sure how exactly you'd like this ticket to move forward. It looks more like an architectural problem more than a feature request for confd. I don't think a docker-specific integration with confd is something we'd likely merge. That would likely have to be a separate tool which confd can call to send SIGHUP to the container (like `docker kill`).

**Comment by mishak87** [comment]
Core of my issue is:
How to pass information that file are ready or have been updated with bare minimum of information and assumptions. (primary service + confd sidekick)

I have posted it here because I don't know about another project that came closer to solving this issue. Probably I should have posted it on mailing list first.

You helped me realize there is yet another option - trigger pipe (file). For example [nullmailer uses](http://www.troubleshooters.com/linux/nullmailer/landmines.htm) to notify send process about new item in queue.

Thanks!

**Comment by bacongobbler** [comment]
So to bring this back to turn into actionable items:

> How to pass information that files are ready or have been updated

That's confd's domain, which you'd use `reload_cmd` to pass along information that confd has updated the template resources.

> with bare minimum of knowledge about primary service and assumptions

That is an application issue and should be handled outside of confd.

Hope this helps!
