### ISSUE TITLE
Cannot connect to remote zookeeper cluster

### ISSUE THREAD

**Issue by elisehuard** [kelseyhightower/confd#424]
I'm having trouble connecting to the zookeeper node(s). It's not a connection problem, the zookeeper cli can connect fine
```
ubuntu@sandpit-logstash:/usr/bin$ /usr/lib/zookeeper/bin/cli_mt 172.20.1.151:2181
Watcher SESSION_EVENT state = CONNECTED_STATE
Got a new session id: 0xa539ebf7debfeba
bye
```
However, if I try to connect with confd (freshly downloaded confd-0.11.0-linux-amd64) I can't connect
```
ubuntu@sandpit-logstash:~$ ./confd-0.11.0-linux-amd64 -onetime -backend zookeeper -log-level=debug -node=172.20.1.151
2016-03-29T10:20:24Z sandpit-logstash ./confd-0.11.0-linux-amd64[12150]: INFO Backend set to zookeeper
2016-03-29T10:20:24Z sandpit-logstash ./confd-0.11.0-linux-amd64[12150]: INFO Starting confd
2016-03-29T10:20:24Z sandpit-logstash ./confd-0.11.0-linux-amd64[12150]: INFO Backend nodes set to 172.20.1.151
2016-03-29T10:20:24Z sandpit-logstash ./confd-0.11.0-linux-amd64[12150]: DEBUG Loading template resources from confdir /etc/confd
2016-03-29T10:20:24Z sandpit-logstash ./confd-0.11.0-linux-amd64[12150]: DEBUG Loading template resource from /etc/confd/conf.d/test.toml
2016-03-29T10:20:24Z sandpit-logstash ./confd-0.11.0-linux-amd64[12150]: DEBUG Retrieving keys from store
2016-03-29T10:20:24Z sandpit-logstash ./confd-0.11.0-linux-amd64[12150]: DEBUG Key prefix set to /
2016-03-29T10:20:24Z sandpit-logstash ./confd-0.11.0-linux-amd64[12150]: ERROR zk: node does not exist
```

zookeeper is version 3.4.6.  Doesn't work if I add the port either (:2181)   What am I doing wrong?

**Comment by HeavyHorst** [comment]
@elisehuard You are connected.

ERROR zk: node does not exist -> You have to create the keys in zookeeper before connecting.

If you have the following config file:
```
[template]
src = "myconfig.conf.tmpl"
dest = "/tmp/myconfig.conf"
keys = [
    "/myapp/database/url",
    "/myapp/database/user",
]
```

then you have to set some values for /myapp/database/url and /myapp/database/user:
```
[zk: localhost:2181(CONNECTED) 1] create /myapp ""
[zk: localhost:2181(CONNECTED) 2] create /myapp/database ""
[zk: localhost:2181(CONNECTED) 3] create /myapp/database/url "db.example.com"
[zk: localhost:2181(CONNECTED) 4] create /myapp/database/user "rob"
```

Take a look at the quickstart_guide for some more examples: https://github.com/kelseyhightower/confd/blob/master/docs/quick-start-guide.md

**Comment by elisehuard** [comment]
Thank you for this, but I did create the keys beforehand:
```
ubuntu@sandpit-logstash:~$ /usr/lib/zookeeper/bin/cli_mt 172.20.1.151:2181
Watcher SESSION_EVENT state = CONNECTED_STATE
Got a new session id: 0xa539ebf7dec0653
ls /myapp/database
time = 1 msec
/myapp/database: rc = 0
	user "rob"
	url "db.example.com"
time = 1 msec
```
so the tree is there
(although my zk cli doesn't like creating branch nodes with "" values, so I did without them. it only accepts values for leaf nodes)
Error stays the same ...

**Comment by bacongobbler** [comment]
The [zookeeper integration tests](https://github.com/kelseyhightower/confd/tree/master/integration/zookeeper) run with [version 3.4.8](https://github.com/kelseyhightower/confd/blob/master/.travis.yml#L35-L38) so it's not a incompatibility issue, I'd assume.

From grepping [mailing lists](http://osdir.com/ml/java-hadoop-zookeeper-user/2010-08/msg00031.html) it sounds like this is a client-side issue when communicating with a cluster. I'm not sure how this would occur but perhaps someone with more knowledge on communicating with a zookeeper cluster would know more.

ping @sheepkiller, any ideas on this one?

**Comment by elisehuard** [comment]
It seems to work when I use the standard zkCli.sh.  I'm happy to close this, since it really seems to be linked to my handling of zookeeper.

**Comment by choco1992** [comment]
Hello @elisehuard 
I 've got a same problem, I use Zookeeper 3.4.10 and the zkCli.sh.
Please, How had you solve it ?

**Comment by okushchenko** [comment]
@choco1992 please, share your confd template and config.

**Comment by choco1992** [comment]
Hello @okushchenko,
thank for answering

There is my conf : 
`/etc/confd/conf.d`
`[root@otvmi580s conf.d]# cat /etc/confd/conf.d/myconfig.toml`
`[template]`
`src = "myconfig.conf.tmpl"`
`dest = "/tmp/myconfig.conf"`
`keys = [`
`    "/myapp/database/url",`
`    "/myapp/database/user",`
`]`

`[root@otvmi580s conf.d]# cat /etc/confd/templates/myconfig.conf.tmpl`
`[myconfig]`
`database_url = {{getv "/myapp/database/url"}}`
`database_user = {{getv "/myapp/database/user"}}`

and there is the log error

`[root@otvmi580s conf.d]# confd -onetime -backend zookeeper -log-level=debug  -node localhost:2181 -watch`
`2017-08-01T13:37:35+02:00 otvmi580s confd[28489]: INFO Backend set to zookeeper`
`2017-08-01T13:37:35+02:00 otvmi580s confd[28489]: INFO Starting confd`
`2017-08-01T13:37:35+02:00 otvmi580s confd[28489]: INFO Backend nodes set to localhost:2181`
`2017-08-01T13:37:35+02:00 otvmi580s confd[28489]: DEBUG Loading template resources from confdir /etc/confd`
`2017-08-01T13:37:35+02:00 otvmi580s confd[28489]: DEBUG Found template: /etc/confd/conf.d/myconfig.toml`
`2017-08-01T13:37:35+02:00 otvmi580s confd[28489]: DEBUG Loading template resource from /etc/confd/conf.d/myconfig.toml`
`2017-08-01T13:37:35+02:00 otvmi580s confd[28489]: DEBUG Retrieving keys from store`
`2017-08-01T13:37:35+02:00 otvmi580s confd[28489]: DEBUG Key prefix set to /`
`2017/08/01 13:37:35 Connected to 127.0.0.1:2181`
`2017/08/01 13:37:35 Authenticated: id=98402608016785427, timeout=4000`
`2017-08-01T13:37:35+02:00 otvmi580s confd[28489]: ERROR zk: node does not exist`
`2017-08-01T13:37:35+02:00 otvmi580s confd[28489]: FATAL zk: node does not exist`

Is it Ok ?
Don't hesitate if you want more informations .

**Comment by okushchenko** [comment]
Please, run these commands from zkCli.sh and copy the ouput:
`ls /myapp`
`ls /myapp/database`
`get /myapp/database/url `
`get /myapp/database/user`

**Comment by choco1992** [comment]
Hi @okushchenko ,

Sorry, for beeing late, I saw my mistake

There is the result of that you asked: 

`[zk: localhost:2181(CONNECTED) 17] ls /myap`
`[database]`
`[zk: localhost:2181(CONNECTED) 17] ls /myap/database`
`[user, url]`
`...`

In fact, I just putted  "myap" instead of "myapp" and the zookeeper was crying, I didn't see ...
I deleted all the tree and built a new tree from scratch, and it work's good without error.

`[zk: localhost:2181(CONNECTED) 17] ls /myapp`
`[database]`
`[zk: localhost:2181(CONNECTED) 17] ls /myapp/database`
`[user, url]`
`[zk: localhost:2181(CONNECTED) 17] get /myapp/database/url`
`test.exple.com`
`cZxid = 0x3000000b8`
`ctime = Tue Aug 01 15:39:28 CEST 2017`
`mZxid = 0x3000000b8`
`mtime = Tue Aug 01 15:39:28 CEST 2017`
`pZxid = 0x3000000b8`
`cversion = 0`
`dataVersion = 0`
`aclVersion = 0`
`ephemeralOwner = 0x0`
`dataLength = 14`
`numChildren = 0`

`[zk: localhost:2181(CONNECTED) 17] get /myapp/database/user`
`test`
`cZxid = 0x3000000b9`
`ctime = Tue Aug 01 15:41:21 CEST 2017`
`mZxid = 0x3000000b9`
`mtime = Tue Aug 01 15:41:21 CEST 2017`
`pZxid = 0x3000000b9`
`cversion = 0`
`dataVersion = 0`
`aclVersion = 0`
`ephemeralOwner = 0x0`
`dataLength = 4`
`numChildren = 0`

I relaunch the confd command and it's ok : 

`[root@otvmi580s zookeeper-3.4.10]# confd -onetime -backend zookeeper -log-level=debug  -node localhost:2181 -watch`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: INFO Backend set to zookeeper`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: INFO Starting confd`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: INFO Backend nodes set to localhost:2181`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: DEBUG Loading template resources from confdir /etc/confd`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: DEBUG Found template: /etc/confd/conf.d/myconfig.toml`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: DEBUG Loading template resource from /etc/confd/conf.d/myconfig.toml`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: DEBUG Retrieving keys from store`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: DEBUG Key prefix set to /`
`2017/08/01 15:50:57 Connected to 127.0.0.1:2181`
`2017/08/01 15:50:57 Authenticated: id=98402608016785441, timeout=4000`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: DEBUG Using source template /etc/confd/templates/myconfig.conf.tmpl`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: DEBUG Compiling source template /etc/confd/templates/myconfig.conf.tmpl`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: DEBUG Comparing candidate config to /tmp/myconfig.conf`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: INFO /tmp/myconfig.conf has md5sum 8e76340b541b8ee29023c001a5e4da18 should be 8b78c28c375618fe50141161c7b304ea`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: INFO Target config /tmp/myconfig.conf out of sync`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: DEBUG Overwriting target config /tmp/myconfig.conf`
`2017-08-01T15:50:57+02:00 otvmi580s confd[3406]: INFO Target config /tmp/myconfig.conf has been updated`

my /tmp/myconfig.conf file has been updated 
`-rw-r--r-- 1 root root 62 Aug  1 15:50 /tmp/myconfig.conf`

A big thank for your help @okushchenko  and verry sorry  to had disrupt you
I would be more attentive the next time

Best regards.

**Comment by okushchenko** [comment]
@choco1992 all good, I'm glad I was able to help.
