### ISSUE TITLE
Release v0.12.0

### ISSUE THREAD

**Issue by sdurrheimer** [kelseyhightower/confd#460]
@kelseyhightower Hi there,

Any plan on releasing the v0.12.0 soon, or at least a new alpha or beta ?

**Comment by pierredup** [comment]
Ping

**Comment by sdurrheimer** [comment]
@carmstrong @gabrtv @bacongobbler @kelseyhightower Anyone ?

**Comment by bacongobbler** [comment]
The only person who can authorize a new release is kelsey, as per https://github.com/kelseyhightower/confd/blob/master/CONTRIBUTING.md#bdfl. He's been busy with other work so sorry about the long wait... We're all maintaining this project on our own free time.

Since it's been a long time I might take a weekend and create a fork with an "unofficial" 0.12 release and maintain the fork, but any official release on the official confd repo has to be signed off by him.

**Comment by bachp** [comment]
It would be good to have 0.12 release as it follows go best practice and is thus much easier to package.

**Comment by bobbytables** [comment]
Hi @kelseyhightower - Is there anything I can do to help get v0.12 out? I know you're busy so if there's any code / documentation I can help write let me know.

**Comment by bacongobbler** [comment]
I've gone ahead and made a v0.12.1 release on my fork that includes many of the PRs here. See [the v0.12.0](https://github.com/bacongobbler/confd/releases/tag/v0.12.0) and [v0.12.1 release notes](https://github.com/bacongobbler/confd/releases/tag/v0.12.1) for more information on the changelog.

Assuming this fork is "dead", I'll be happy to continue maintaining confd there.

**Comment by johntdyer** [comment]
@kelseyhightower any chance of an official 0.12 release ?

**Comment by okushchenko** [comment]
0.12.0 release is already here:
https://github.com/kelseyhightower/confd/releases/tag/v0.12.0
