### ISSUE TITLE
Confd spawning application hijacks stdout logging in Docker

### ISSUE THREAD

**Issue by caio1982** [kelseyhightower/confd#513]
CMD bin/confd -confdir etc/confd/ -log-level info -backend etcd -node http://etcd-client:2379

Hi, so I am using this Dockerfile command to make confd spawn my own application so it can monitor key changes in my etcd instance and automatically reload and check everything for me. However, because confd is monitoring the spawned app, it is logging to Docker's log file (stdout) only confd messages not my app messages any more, as it used to be before confd.

Is confd hijacking my app logging because I don't use -onetime with it? Is there a workaround for this?

**Comment by HeavyHorst** [comment]
I would use something like s6 or another lightweight init system to spawn the processes (including confd).
Confd isn't really meant to spawn and monitor subprocesses.

You may also get some problems with zombie processes if you have more than 1 process per container without an init system (https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/) -- i ran into this with a simple haproxy setup.

**Comment by bacongobbler** [comment]
It's a common misconception that docker picks up on anything shipped to STDOUT. This is incorrect. Docker picks up on anything shipped to PID 1's STDOUT.

The reason this doesn't work is because `/dev/stdout` is a link to STDOUT of the process accessing it. So by letting confd run as PID 1 and booting your application inside the container as part of confd, anything it logs will not be shipped to `docker logs`.

What you want to do is to redirect output to STDOUT of PID 1 (in this case, `confd`). PID 1 is the process launched by docker, and its STDOUT will be what docker picks up.

A much better solution would be to use an init system like what @HeavyHorst suggests. No init system = zombies.
