### ISSUE TITLE
can't get key /something/with_an_underscore from env backend

### ISSUE THREAD

**Issue by bvdeenen** [kelseyhightower/confd#531]
I have a key defined as `/kafka/broker_id/host1` and I can't find a way to set it from the `env` backend.
Is there no way ?
I've tried export KAFKA_BROKER_ID_KAFKA1=... but I get (with `-log-level debug`)

    confd[98]: DEBUG Key Map: map[string]string{"/kafka/broker/id/kafka1":"5"}
    confd[98]: DEBUG Using source template /etc/confd/templates/server.properties.tmpl
    confd[98]: DEBUG Compiling source template /etc/confd/templates/server.properties.tmpl
    confd[98]: ERROR template: server.properties.tmpl:24:13: executing "server.properties.tmpl" at <getv (print "/kafka/...>: error calling getv: key does not exist: /kafka/broker_id/kafka1

Is there a workaround, apart from removing the underscores in my keys?

**Comment by HeavyHorst** [comment]
For the env backend every _ is replaced with an / at the moment. Your key is /kafka/broker/id/kafka1.
There is no way to treat the _ not as a path separator.

**Comment by stela** [comment]
This bit me too, I have an existing docker image with which works together with the consul backend, containing
`{{getv "/xmpp_domain"}}`
Now I'd like to use the "env" backend (for a kubernetes environment) instead, but the same docker image.
Prefix-matching is done against `XMPP_DOMAIN` which is the name of my environment variable. However, before returning the configuration mappings, the key is converted to `/xmpp/domain` which later on causes errors: `... error calling getv: key does not exist: /xmpp_domain`

When you request for a key containing an underscore, that's probably what you want the backend to return. What would happen if you modified env/client.go like this:
`vars[key] = envValue`
instead of
`vars[clean(envKey)] = envValue`?

**Comment by stela** [comment]
Posted pull request #567, let me know what you think about it.
