### ISSUE TITLE
conf.d/ files should be dynamic

### ISSUE THREAD

**Issue by fritzy** [kelseyhightower/confd#79]
Use case:
dev environment, easy script install of confd configuration, but nginx needs full path to the output file, so `dest = "$OUTPUTDIR/nginx.conf"` or `dest = {{nginx_conf_dir}}/nginx.conf` or something like that.

**Comment by durzo** [comment]
I have a need for this also.

I want to use confd to create config files based on etcd info, the structure looking like:

/app1/database/url
/app1/database/user
/app2/database/url
/app2/database/user

The problem is we have literally thousands (scaling to hundreds of thousands) of appX's, and they grow dynamically based on user signup.

we can already use a shared template to generate the dest file dynamically with confd, but we cannot specify dynamic dest files in the conf.d/ toml file.

While I understand this changes the design of confd, It seems like it would be a very trivial change to support this feature.

I have thought long and hard how to work around this, but any solution which auto-creates the toml files could just as well create the resulting template config file too rendering confd irrelevant, and that makes me sad because its an awesome project.

Forgive me if I should have created a new issue for this
